name: OrgXcelii
favicon: null
layout_spectrum: 0.98703
typography_spectrum: 0.498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce6ef'
    - '#c3d4dc'
    - '#9fbed0'
    - '#75929a'
    - '#5b7782'
  brandStrength: 0.8162087732926011
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
